name: Deploy WebApp to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Получаем код
      - uses: actions/checkout@v3

      # 2. Устанавливаем Node (если нужны сборки, иначе можно пропустить)
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Пушим webapp напрямую в gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webapp
          publish_branch: gh-pages
          force_orphan: true
